# Generated by Django 4.1.1 on 2022-10-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inStock",
            field=models.BooleanField(default=False),
        ),
    ]
